version: '3'
services:
  web_backend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    container_name: library_service
    volumes:
      - './:/code'