version: '3'
services:
  web_backend:
    build:
      context: .
    ports:
      - '80:80'
    container_name: library_service
    volumes:
      - './:/code'
    depends_on:
      - smtp

  smtp:
    image: namshi/smtp
    restart: always
    ports:
      - '25:25'
    volumes:
      - './:/code'
    container_name: smtp